version: "3.6"

services:
    rabbitmq:
        image: rabbitmq:3.11-management
        container_name: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - ms-network
        volumes:
            - ./dados/rabbitmq:/var/lib/rabbitmq/
        environment:
            - RABBITMQ_DEFAULT_USER=hugo
            - RABBITMQ_DEFAULT_PASS=root

    mysqldb:
        image: mysql
        container_name: mysqldb
        restart: always
        ports: 
            - 3306:3306
        volumes:
            - ./dados/db:/var/lib/mysql/
        networks:
            - ms-network
        environment:
            - MYSQL_ROOT_USERNAME=root
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=minifood-db

    eureka-server:
        image: 0miniugo/minifood-server-ms
        container_name: eureka-server
        ports:
            - 8081:8081
        networks:
            - ms-network
        environment:
            eureka.instance.hostname: eureka-server
            eureka.client.serviceUrl.defaultZone: http://eureka-server:8081/eureka/
            eureka.client.register-with-eureka: false
            eureka.client.fetch-registry: false

    gateway:
        image: 0miniugo/minifood-gateway-ms
        container_name: gateway-ms
        ports:
            - 8082:8082
        networks:
            - ms-network
        depends_on:
            - eureka-server
            - pedidos-ms
            - pagamentos-ms
        environment:
            eureka.client.serviceUrl.defaultZone: http://eureka-server:8081/eureka/
            spring.cloud.gateway.discovery.locator.enabled: true
            spring.cloud.gateway.discovery.locator.lowerCaseServiceId: true
            spring.application.name: gateway

    pedidos-ms:
        image: 0miniugo/minifood-pedidos-ms
        container_name: pedidos-ms
        ports:
            - 8091:8091
        networks:
            - ms-network
        depends_on:
            - eureka-server
            - mysqldb
            - rabbitmq
        environment:
            spring.application.name: pedidos-ms
            eureka.client.serviceUrl.defaultZone: http://eureka-server:8081/eureka/
            spring.rabbitmq.host: rabbitmq
            spring.datasource.url: jdbc:mysql://mysqldb:3306/minifood-db-pedidos?createDatabaseIfNotExist=true
    
    pagamentos-ms:
        image: 0miniugo/minifood-pagamentos-ms
        container_name: pagamentos-ms
        ports:
            - 8092:8092
        networks:
            - ms-network
        depends_on:
            - eureka-server
            - mysqldb
            - rabbitmq
        environment:
            spring.application.name: pagamentos-ms
            eureka.client.serviceUrl.defaultZone: http://eureka-server:8081/eureka/
            spring.rabbitmq.host: rabbitmq
            spring.datasource.url: jdbc:mysql://mysqldb:3306/minifood-db-pagamentos?createDatabaseIfNotExist=true

    avaliacao-ms:
        image: 0miniugo/minifood-avaliacao-ms
        container_name: avaliacao-ms
        ports:
            - 8093:8093
        networks:
            - ms-network
        depends_on:
            - rabbitmq
        environment:
            spring.rabbitmq.host: rabbitmq

networks:
    ms-network:
        driver: bridge
